### ISSUE TITLE
gevent 1.4.0 and urllib3 1.22 does not work with requests 2.20.1

### ISSUE THREAD

**Issue by a82singh** [requests/requests#4948]
## Expected Result

My python module is executed successfully with the following:

gevent 1.4.0, urllib3 1.22  work with requests 2.10.0 with no error

## Actual Result

but with 

gevent 1.4.0, urllib3 1.22  with requests 2.20.1 gives

  File "/home/abc/xyz/lib/python2.7/site-packages/urllib3/util/wait.py", line 33, in wait_for_read
    return _wait_for_io_events(socks, EVENT_READ, timeout)
  File "/home/abc/xyz/lib/python2.7/site-packages/urllib3/util/wait.py", line 22, in _wait_for_io_events
    with DefaultSelector() as selector:
  File "/home/abc/xyz/lib/python2.7/site-packages/urllib3/util/selectors.py", line 581, in DefaultSelector
    return _DEFAULT_SELECTOR()
  File "/home/abc/xyz/lib/python2.7/site-packages/urllib3/util/selectors.py", line 394, in __init__
    self._epoll = select.epoll()
AttributeError: 'module' object has no attribute 'epoll'

There is absolutely no changes in our code and gevent.monkey.patch_all() is the first statement before any imports.

## System Information

    $ python -m requests.help

{
  "chardet": {
    "version": "3.0.4"
  }, 
  "cryptography": {
    "version": ""
  }, 
  "idna": {
    "version": "2.6"
  }, 
  "implementation": {
    "name": "CPython", 
    "version": "2.7.15"
  }, 
  "platform": {
    "release": "3.10.0-693.2.2.el7.x86_64", 
    "system": "Linux"
  }, 
  "pyOpenSSL": {
    "openssl_version": "", 
    "version": null
  }, 
  "requests": {
    "version": "2.21.0"
  }, 
  "system_ssl": {
    "version": "1000105f"
  }, 
  "urllib3": {
    "version": "1.22"
  }, 
  "using_pyopenssl": false
}

**Comment by sethmlarson** [comment]
You should try upgrading to a newer version of urllib3. When we first added selectors we had many people coming to us with monkey-patching problems. Essentially due to incorrect import ordering urllib3 used to detect that `select.epoll` was available but then gevent patches it out and then when we go to use `select.epoll` it's no longer there and we get this error. This is fixed in newer versions of urllib3 (even though it's not *really* our fault).

**Comment by sigmavirus24** [comment]
2.20.1 isn't supported any longer

**Comment by a82singh** [comment]
Works with the following:

"requests": {
    "version": "2.21.0"
  }, 
  "urllib3": {
    "version": "1.24.1"
  },
  "gevent": {
    "version": "1.4.0"
  } 

Thanks !
